name: fedupxp

channels:
  - default
  - conda-forge

dependencies:
  - python
  - seaborn
  - altair
  - numpy
  - gdown
  - matplotlib
  - SPARQLWrapper
  - notebook
  - pandas
  - setuptools
  - requests
  - click
  - pip
  - pip:
    - snakemake